version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:53:53"                #
      - "127.0.0.1:53:53/udp"            #
      - "127.0.0.1:443:443"              #
      - "127.0.0.1:4510-4530:4510-4530"  # ext services port range
      - "127.0.0.1:4571:4571"            #
    environment:
      - DEBUG=0
      - SERVICES=sqs
      - EDGE_PORT=4566
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1
      - AWS_DEFAULT_REGION=eu-south-1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  backend:
    build: backend
    ports:
      - 80:8080
    environment:
      - NODE_ENV=production
      - AWS_ENDPOINT=http://localhost:4566
      - AWS_REGION=eu-south-1
      - AWS_ACCESS_KEY_ID=na
      - AWS_SECRET_ACCESS_KEY=na
      - AWS_QUEUE_URL=http://localhost:4566/000000000000/votes
    restart: always
