version: '3.8'

services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=docker
      - PORT=8080
      - AWS_ENDPOINT=http://127.0.0.1:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_QUEUE_NAME=votes
      - AWS_TABLE_NAME=Polls
    restart: always

  worker:
    build: worker
    environment:
      - NODE_ENV=docker
      - AWS_ENDPOINT=http://127.0.0.1:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_QUEUE_NAME=votes
      - AWS_TABLE_NAME=Polls
    restart: always
