version: '3.8'

services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=docker
      - PORT=8080
      - AWS_ENDPOINT=http://127.0.0.1:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_QUEUE_URL=http://locastack:4566/000000000000/votes
    restart: always
