version: '3.8'

services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=docker
      - PORT=8080
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=eu-south-1
      - AWS_ACCESS_KEY_ID=na
      - AWS_SECRET_ACCESS_KEY=na
      - AWS_QUEUE_URL=http://locastack:4566/000000000000/votes
    restart: always
