version: '3.8'

services:
  backend:
    build: backend
    ports:
      - 80:8080
    environment:
      - NODE_ENV=production
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SQS_BASE_URL=https://sqs.us-west-2.amazonaws.com/123456789012
    restart: always
