version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    restart: always

  mongo:
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb_data:/data/db
    restart: always

  backend:
    image: docker.io/plfiorini/voting-backend:latest
    build: backend
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=empty
      - PORT=8080
      - QUEUE_BACKEND=amqp
      - DATABASE_BACKEND=mongodb
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - MONGODB_URL=mongodb://mongoadmin:secret@mongo:27017
    restart: always

  worker:
    image: docker.io/plfiorini/voting-worker:latest
    build: worker
    environment:
      - NODE_ENV=empty
      - QUEUE_BACKEND=amqp
      - DATABASE_BACKEND=mongodb
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - MONGODB_URL=mongodb://mongoadmin:secret@mongo:27017
    restart: always

volumes:
  rabbitmq_data:
  rabbitmq_logs:
  mongodb_data:
