apiVersion: apps/v1
kind: DeploymentConfig
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: plfiorini/voting-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: AWS_REGION
              value: us-west-2
            - name: AWS_ACCESS_KEY_ID
              value: X
            - name: AWS_SECRET_ACCESS_KEY
              value: X
            - name: AWS_SQS_BASE_URL
              value: https://sqs.us-west-2.amazonaws.com/123456789012
          command: ["npm", "run", "start"]
