apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: plfiorini/voting-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: empty
            - name: PORT
              value: "8080"
            - name: QUEUE_BACKEND
              value: amqp
            - name: DATABASE_BACKEND
              value: mongodb
            - name: AMQP_URL
              value: amqp://guest:guest@rabbitmq.voting.svc.cluster.local:5672
            - name: MONGODB_URL
              value: mongodb://mongoadmin:secret@mongodb.voting.svc.cluster.local:27017
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: voting
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
