apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: plfiorini/voting-worker:latest
          env:
            - name: NODE_ENV
              value: empty
            - name: QUEUE_BACKEND
              value: amqp
            - name: DATABASE_BACKEND
              value: mongodb
            - name: AMQP_URL
              value: amqp://guest:guest@rabbitmq.voting.svc.cluster.local:5672
            - name: MONGODB_URL
              value: mongodb://mongoadmin:secret@mongodb.voting.svc.cluster.local:27017
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
